spring:
  datasource:
    username: admin
    url: jdbc:h2:mem:userdb
    driverClassName: org.h2.Driver
    password: nimda
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update